const restaurants = [
  {
    image: "sixth",
    name: "Heritage Haveli",
    rating: "4.2",
    food_type: "Healthy Food",
    price_for_two: 2354,
    location: "Kalkaji",
    distance: "3.8",
    offers: 17,
    alcohol: false,
    rest_opening_time: 6,
    rest_closing_time: 18,
  },
  {
    image: "second",
    name: "Punjabi Zaika",
    rating: "4.5",
    food_type: "Vegan",
    price_for_two: 2017,
    location: "Saket",
    distance: "9.5",
    offers: 0,
    alcohol: true,
    rest_opening_time: 1,
    rest_closing_time: 13,
  },
  {
    image: "fifth",
    name: "Spice Junction",
    rating: "5.0",
    food_type: "Cafe",
    price_for_two: 2175,
    location: "Punjabi Bagh",
    distance: "5.9",
    offers: 5,
    alcohol: true,
    rest_opening_time: 4,
    rest_closing_time: 16,
  },
  {
    image: "sixth",
    name: "Urban Tadka",
    rating: "2.1",
    food_type: "Mughlai",
    price_for_two: 644,
    location: "Greater Kailash",
    distance: "1.4",
    offers: 16,
    alcohol: false,
    rest_opening_time: 10,
    rest_closing_time: 22,
  },
  {
    image: "first",
    name: "Rasoi Express",
    rating: "2.5",
    food_type: "Biryani",
    price_for_two: 119,
    location: "Rohini",
    distance: "1.6",
    offers: 10,
    alcohol: false,
    rest_opening_time: 21,
    rest_closing_time: 9,
  },
  {
    image: "first",
    name: "Urban Tadka",
    rating: "1.4",
    food_type: "Healthy Food",
    price_for_two: 2070,
    location: "Pitampura",
    distance: "8.7",
    offers: 10,
    alcohol: false,
    rest_opening_time: 15,
    rest_closing_time: 3,
  },
  {
    image: "first",
    name: "Spice Junction",
    rating: "4.7",
    food_type: "Cafe",
    price_for_two: 1653,
    location: "Punjabi Bagh",
    distance: "9.6",
    offers: 27,
    alcohol: false,
    rest_opening_time: 16,
    rest_closing_time: 4,
  },
  {
    image: "first",
    name: "Bombay Bistro",
    rating: "2.1",
    food_type: "Fast Food",
    price_for_two: 1607,
    location: "Mayur Vihar",
    distance: "6.9",
    offers: 8,
    alcohol: false,
    rest_opening_time: 16,
    rest_closing_time: 4,
  },
  {
    image: "tenth",
    name: "Delhi Darbar",
    rating: "3.9",
    food_type: "Kebab",
    price_for_two: 1553,
    location: "Punjabi Bagh",
    distance: "9.8",
    offers: 0,
    alcohol: false,
    rest_opening_time: 22,
    rest_closing_time: 10,
  },
  {
    image: "second",
    name: "Rasoi Express",
    rating: "2.7",
    food_type: "Healthy Food",
    price_for_two: 1336,
    location: "Kalkaji",
    distance: "9.2",
    offers: 15,
    alcohol: false,
    rest_opening_time: 7,
    rest_closing_time: 19,
  },
  {
    image: "sixth",
    name: "Urban Tadka",
    rating: "3.9",
    food_type: "Healthy Food",
    price_for_two: 2168,
    location: "Punjabi Bagh",
    distance: "4.0",
    offers: 9,
    alcohol: false,
    rest_opening_time: 6,
    rest_closing_time: 18,
  },
  {
    image: "first",
    name: "Bombay Bistro",
    rating: "4.9",
    food_type: "Bakery",
    price_for_two: 912,
    location: "Greater Kailash",
    distance: "4.1",
    offers: 24,
    alcohol: true,
    rest_opening_time: 19,
    rest_closing_time: 7,
  },
  {
    image: "first",
    name: "Spice Route",
    rating: "4.7",
    food_type: "Mughlai",
    price_for_two: 1770,
    location: "Civil Lines",
    distance: "3.1",
    offers: 2,
    alcohol: false,
    rest_opening_time: 10,
    rest_closing_time: 22,
  },
  {
    image: "tenth",
    name: "Kebab Kingdom",
    rating: "3.7",
    food_type: "Fusion",
    price_for_two: 1487,
    location: "Kalkaji",
    distance: "4.7",
    offers: 8,
    alcohol: false,
    rest_opening_time: 17,
    rest_closing_time: 5,
  },
  {
    image: "fourth",
    name: "Flavours of India",
    rating: "4.9",
    food_type: "Thai",
    price_for_two: 284,
    location: "Pitampura",
    distance: "3.4",
    offers: 6,
    alcohol: false,
    rest_opening_time: 1,
    rest_closing_time: 13,
  },
  {
    image: "tenth",
    name: "Tandoori Nights",
    rating: "3.1",
    food_type: "Fusion",
    price_for_two: 727,
    location: "Chandni Chowk",
    distance: "1.5",
    offers: 28,
    alcohol: true,
    rest_opening_time: 5,
    rest_closing_time: 17,
  },
  {
    image: "tenth",
    name: "Saffron Grill",
    rating: "1.8",
    food_type: "Kebab",
    price_for_two: 1200,
    location: "Lajpat Nagar",
    distance: "3.2",
    offers: 13,
    alcohol: false,
    rest_opening_time: 18,
    rest_closing_time: 6,
  },
  {
    image: "seventh",
    name: "Delhi Darbar",
    rating: "2.1",
    food_type: "Continental",
    price_for_two: 211,
    location: "Hauz Khas",
    distance: "1.1",
    offers: 19,
    alcohol: false,
    rest_opening_time: 17,
    rest_closing_time: 5,
  },
  {
    image: "fourth",
    name: "Royal Tandoor",
    rating: "4.7",
    food_type: "Continental",
    price_for_two: 2212,
    location: "Rohini",
    distance: "9.2",
    offers: 26,
    alcohol: false,
    rest_opening_time: 6,
    rest_closing_time: 18,
  },
  {
    image: "fourth",
    name: "Curry Leaf",
    rating: "4.0",
    food_type: "Punjabi",
    price_for_two: 2250,
    location: "Chandni Chowk",
    distance: "5.0",
    offers: 25,
    alcohol: false,
    rest_opening_time: 17,
    rest_closing_time: 5,
  },
  {
    image: "second",
    name: "Heritage Haveli",
    rating: "3.2",
    food_type: "Cafe",
    price_for_two: 160,
    location: "Rajouri Garden",
    distance: "1.9",
    offers: 10,
    alcohol: false,
    rest_opening_time: 10,
    rest_closing_time: 22,
  },
  {
    image: "ninth",
    name: "Heritage Haveli",
    rating: "3.5",
    food_type: "Cafe",
    price_for_two: 696,
    location: "Punjabi Bagh",
    distance: "9.7",
    offers: 19,
    alcohol: true,
    rest_opening_time: 19,
    rest_closing_time: 7,
  },
  {
    image: "first",
    name: "Urban Tadka",
    rating: "1.1",
    food_type: "Bakery",
    price_for_two: 794,
    location: "Pitampura",
    distance: "9.3",
    offers: 13,
    alcohol: true,
    rest_opening_time: 13,
    rest_closing_time: 1,
  },
  {
    image: "first",
    name: "The Curry Club",
    rating: "3.3",
    food_type: "Vegan",
    price_for_two: 2149,
    location: "Preet Vihar",
    distance: "5.0",
    offers: 13,
    alcohol: false,
    rest_opening_time: 11,
    rest_closing_time: 23,
  },
  {
    image: "seventh",
    name: "Spice Route",
    rating: "4.1",
    food_type: "South Indian",
    price_for_two: 1371,
    location: "Rohini",
    distance: "8.7",
    offers: 12,
    alcohol: false,
    rest_opening_time: 21,
    rest_closing_time: 9,
  },
  {
    image: "third",
    name: "Bombay Bistro",
    rating: "2.8",
    food_type: "Desserts",
    price_for_two: 2262,
    location: "Punjabi Bagh",
    distance: "6.0",
    offers: 29,
    alcohol: false,
    rest_opening_time: 20,
    rest_closing_time: 8,
  },
  {
    image: "tenth",
    name: "Taste of Punjab",
    rating: "1.1",
    food_type: "Vegan",
    price_for_two: 741,
    location: "Karol Bagh",
    distance: "1.8",
    offers: 28,
    alcohol: true,
    rest_opening_time: 8,
    rest_closing_time: 20,
  },
  {
    image: "fifth",
    name: "Tandoori Nights",
    rating: "2.2",
    food_type: "Desserts",
    price_for_two: 2086,
    location: "Saket",
    distance: "6.1",
    offers: 18,
    alcohol: false,
    rest_opening_time: 8,
    rest_closing_time: 20,
  },
  {
    image: "fifth",
    name: "The Curry Club",
    rating: "4.1",
    food_type: "Healthy Food",
    price_for_two: 1587,
    location: "Punjabi Bagh",
    distance: "8.4",
    offers: 11,
    alcohol: true,
    rest_opening_time: 4,
    rest_closing_time: 16,
  },
  {
    image: "fifth",
    name: "Saffron Grill",
    rating: "4.7",
    food_type: "Chinese",
    price_for_two: 1769,
    location: "Greater Kailash",
    distance: "9.5",
    offers: 25,
    alcohol: false,
    rest_opening_time: 14,
    rest_closing_time: 2,
  },
  {
    image: "eighth",
    name: "Punjabi Zaika",
    rating: "1.3",
    food_type: "Kebab",
    price_for_two: 979,
    location: "Hauz Khas",
    distance: "11.0",
    offers: 25,
    alcohol: false,
    rest_opening_time: 4,
    rest_closing_time: 16,
  },
  {
    image: "second",
    name: "Kebab Kingdom",
    rating: "4.4",
    food_type: "Vegan",
    price_for_two: 1414,
    location: "Chandni Chowk",
    distance: "2.5",
    offers: 6,
    alcohol: true,
    rest_opening_time: 14,
    rest_closing_time: 2,
  },
  {
    image: "third",
    name: "Desi Bites",
    rating: "2.4",
    food_type: "North Indian",
    price_for_two: 521,
    location: "Janakpuri",
    distance: "5.1",
    offers: 0,
    alcohol: false,
    rest_opening_time: 2,
    rest_closing_time: 14,
  },
  {
    image: "fourth",
    name: "Royal Tandoor",
    rating: "2.2",
    food_type: "Thai",
    price_for_two: 1694,
    location: "South Extension",
    distance: "4.5",
    offers: 9,
    alcohol: true,
    rest_opening_time: 22,
    rest_closing_time: 10,
  },
  {
    image: "ninth",
    name: "Punjabi Zaika",
    rating: "1.2",
    food_type: "Seafood",
    price_for_two: 1220,
    location: "Chandni Chowk",
    distance: "3.1",
    offers: 19,
    alcohol: true,
    rest_opening_time: 18,
    rest_closing_time: 6,
  },
  {
    image: "seventh",
    name: "Rasoi Express",
    rating: "1.9",
    food_type: "Punjabi",
    price_for_two: 2204,
    location: "Saket",
    distance: "9.3",
    offers: 7,
    alcohol: false,
    rest_opening_time: 2,
    rest_closing_time: 14,
  },
  {
    image: "third",
    name: "Kebab Kingdom",
    rating: "3.0",
    food_type: "North Indian",
    price_for_two: 1496,
    location: "Hauz Khas",
    distance: "10.7",
    offers: 1,
    alcohol: false,
    rest_opening_time: 12,
    rest_closing_time: 0,
  },
  {
    image: "first",
    name: "Taste of Punjab",
    rating: "2.7",
    food_type: "Biryani",
    price_for_two: 899,
    location: "Connaught Place",
    distance: "8.1",
    offers: 5,
    alcohol: true,
    rest_opening_time: 0,
    rest_closing_time: 12,
  },
  {
    image: "ninth",
    name: "Street Zaika",
    rating: "2.5",
    food_type: "Seafood",
    price_for_two: 743,
    location: "Karol Bagh",
    distance: "3.0",
    offers: 27,
    alcohol: false,
    rest_opening_time: 8,
    rest_closing_time: 20,
  },
  {
    image: "seventh",
    name: "Saffron Grill",
    rating: "2.9",
    food_type: "Desserts",
    price_for_two: 1433,
    location: "Kalkaji",
    distance: "4.9",
    offers: 1,
    alcohol: true,
    rest_opening_time: 14,
    rest_closing_time: 2,
  },
  {
    image: "fourth",
    name: "Royal Tandoor",
    rating: "2.5",
    food_type: "Fast Food",
    price_for_two: 1841,
    location: "Kalkaji",
    distance: "2.3",
    offers: 9,
    alcohol: true,
    rest_opening_time: 16,
    rest_closing_time: 4,
  },
  {
    image: "ninth",
    name: "Spice Route",
    rating: "3.0",
    food_type: "Mughlai",
    price_for_two: 1606,
    location: "Mayur Vihar",
    distance: "7.6",
    offers: 15,
    alcohol: false,
    rest_opening_time: 0,
    rest_closing_time: 12,
  },
  {
    image: "third",
    name: "Taste of Punjab",
    rating: "4.6",
    food_type: "Continental",
    price_for_two: 1706,
    location: "Greater Kailash",
    distance: "1.8",
    offers: 0,
    alcohol: false,
    rest_opening_time: 10,
    rest_closing_time: 22,
  },
  {
    image: "fifth",
    name: "Kebab Kingdom",
    rating: "2.1",
    food_type: "Vegan",
    price_for_two: 758,
    location: "Karol Bagh",
    distance: "8.9",
    offers: 11,
    alcohol: false,
    rest_opening_time: 16,
    rest_closing_time: 4,
  },
  {
    image: "fifth",
    name: "Punjabi Zaika",
    rating: "1.5",
    food_type: "Fusion",
    price_for_two: 1050,
    location: "Malviya Nagar",
    distance: "6.2",
    offers: 20,
    alcohol: false,
    rest_opening_time: 7,
    rest_closing_time: 19,
  },
  {
    image: "sixth",
    name: "Spice Route",
    rating: "2.2",
    food_type: "Kebab",
    price_for_two: 1497,
    location: "Janakpuri",
    distance: "10.2",
    offers: 6,
    alcohol: true,
    rest_opening_time: 3,
    rest_closing_time: 15,
  },
  {
    image: "tenth",
    name: "Spice Route",
    rating: "3.1",
    food_type: "Punjabi",
    price_for_two: 2046,
    location: "Lajpat Nagar",
    distance: "4.6",
    offers: 15,
    alcohol: false,
    rest_opening_time: 21,
    rest_closing_time: 9,
  },
  {
    image: "third",
    name: "Spice Junction",
    rating: "1.2",
    food_type: "South Indian",
    price_for_two: 1215,
    location: "Civil Lines",
    distance: "6.6",
    offers: 12,
    alcohol: false,
    rest_opening_time: 22,
    rest_closing_time: 10,
  },
  {
    image: "eighth",
    name: "Street Zaika",
    rating: "1.3",
    food_type: "Cafe",
    price_for_two: 1171,
    location: "Karol Bagh",
    distance: "9.2",
    offers: 5,
    alcohol: false,
    rest_opening_time: 18,
    rest_closing_time: 6,
  },
  {
    image: "first",
    name: "Tandoori Nights",
    rating: "4.8",
    food_type: "Mughlai",
    price_for_two: 972,
    location: "Saket",
    distance: "3.1",
    offers: 21,
    alcohol: false,
    rest_opening_time: 10,
    rest_closing_time: 22,
  },
  {
    image: "fourth",
    name: "The Mughal Kitchen",
    rating: "1.5",
    food_type: "Mexican",
    price_for_two: 468,
    location: "Rohini",
    distance: "10.9",
    offers: 7,
    alcohol: false,
    rest_opening_time: 21,
    rest_closing_time: 9,
  },
  {
    image: "third",
    name: "Bombay Bistro",
    rating: "3.5",
    food_type: "Vegan",
    price_for_two: 2111,
    location: "South Extension",
    distance: "8.2",
    offers: 14,
    alcohol: true,
    rest_opening_time: 7,
    rest_closing_time: 19,
  },
  {
    image: "third",
    name: "The Curry Club",
    rating: "1.7",
    food_type: "Mexican",
    price_for_two: 1097,
    location: "Malviya Nagar",
    distance: "7.4",
    offers: 27,
    alcohol: false,
    rest_opening_time: 0,
    rest_closing_time: 12,
  },
  {
    image: "seventh",
    name: "Spice Junction",
    rating: "3.3",
    food_type: "South Indian",
    price_for_two: 656,
    location: "Vasant Kunj",
    distance: "6.7",
    offers: 20,
    alcohol: true,
    rest_opening_time: 11,
    rest_closing_time: 23,
  },
  {
    image: "third",
    name: "Punjabi Zaika",
    rating: "2.6",
    food_type: "Mughlai",
    price_for_two: 1184,
    location: "Dwarka",
    distance: "7.7",
    offers: 23,
    alcohol: false,
    rest_opening_time: 23,
    rest_closing_time: 11,
  },
  {
    image: "fifth",
    name: "The Curry Club",
    rating: "1.5",
    food_type: "Street Food",
    price_for_two: 1277,
    location: "Pitampura",
    distance: "2.6",
    offers: 28,
    alcohol: false,
    rest_opening_time: 9,
    rest_closing_time: 21,
  },
  {
    image: "third",
    name: "Rasoi Express",
    rating: "3.2",
    food_type: "Bakery",
    price_for_two: 1344,
    location: "Janakpuri",
    distance: "8.8",
    offers: 5,
    alcohol: false,
    rest_opening_time: 3,
    rest_closing_time: 15,
  },
  {
    image: "seventh",
    name: "Tandoori Nights",
    rating: "2.8",
    food_type: "Punjabi",
    price_for_two: 309,
    location: "Pitampura",
    distance: "1.2",
    offers: 25,
    alcohol: false,
    rest_opening_time: 2,
    rest_closing_time: 14,
  },
  {
    image: "ninth",
    name: "Desi Bites",
    rating: "1.2",
    food_type: "Healthy Food",
    price_for_two: 1244,
    location: "Vasant Kunj",
    distance: "5.0",
    offers: 19,
    alcohol: false,
    rest_opening_time: 13,
    rest_closing_time: 1,
  },
  {
    image: "fourth",
    name: "Rasoi Express",
    rating: "2.7",
    food_type: "Desserts",
    price_for_two: 544,
    location: "Preet Vihar",
    distance: "2.0",
    offers: 20,
    alcohol: true,
    rest_opening_time: 20,
    rest_closing_time: 8,
  },
  {
    image: "second",
    name: "Masala House",
    rating: "3.5",
    food_type: "Fast Food",
    price_for_two: 694,
    location: "Saket",
    distance: "5.9",
    offers: 20,
    alcohol: false,
    rest_opening_time: 12,
    rest_closing_time: 0,
  },
  {
    image: "first",
    name: "Curry Leaf",
    rating: "2.7",
    food_type: "Continental",
    price_for_two: 2449,
    location: "Punjabi Bagh",
    distance: "9.4",
    offers: 6,
    alcohol: false,
    rest_opening_time: 22,
    rest_closing_time: 10,
  },
  {
    image: "third",
    name: "Royal Tandoor",
    rating: "1.7",
    food_type: "Punjabi",
    price_for_two: 620,
    location: "Civil Lines",
    distance: "9.2",
    offers: 27,
    alcohol: false,
    rest_opening_time: 5,
    rest_closing_time: 17,
  },
  {
    image: "ninth",
    name: "Royal Tandoor",
    rating: "1.0",
    food_type: "Cafe",
    price_for_two: 870,
    location: "Rajouri Garden",
    distance: "5.5",
    offers: 1,
    alcohol: true,
    rest_opening_time: 7,
    rest_closing_time: 19,
  },
  {
    image: "fourth",
    name: "Kebab Kingdom",
    rating: "1.3",
    food_type: "Punjabi",
    price_for_two: 1811,
    location: "Karol Bagh",
    distance: "5.7",
    offers: 29,
    alcohol: true,
    rest_opening_time: 16,
    rest_closing_time: 4,
  },
  {
    image: "fifth",
    name: "Punjabi Zaika",
    rating: "2.9",
    food_type: "Seafood",
    price_for_two: 149,
    location: "Punjabi Bagh",
    distance: "5.9",
    offers: 15,
    alcohol: true,
    rest_opening_time: 6,
    rest_closing_time: 18,
  },
  {
    image: "seventh",
    name: "The Curry Club",
    rating: "1.8",
    food_type: "Kebab",
    price_for_two: 1051,
    location: "Preet Vihar",
    distance: "7.9",
    offers: 2,
    alcohol: false,
    rest_opening_time: 12,
    rest_closing_time: 0,
  },
  {
    image: "third",
    name: "Street Zaika",
    rating: "2.0",
    food_type: "Fast Food",
    price_for_two: 123,
    location: "Malviya Nagar",
    distance: "5.8",
    offers: 24,
    alcohol: false,
    rest_opening_time: 7,
    rest_closing_time: 19,
  },
  {
    image: "tenth",
    name: "Flavours of India",
    rating: "4.5",
    food_type: "Chinese",
    price_for_two: 1510,
    location: "Lajpat Nagar",
    distance: "5.0",
    offers: 10,
    alcohol: false,
    rest_opening_time: 2,
    rest_closing_time: 14,
  },
  {
    image: "first",
    name: "Taste of Punjab",
    rating: "3.5",
    food_type: "Mughlai",
    price_for_two: 331,
    location: "South Extension",
    distance: "1.7",
    offers: 15,
    alcohol: false,
    rest_opening_time: 17,
    rest_closing_time: 5,
  },
  {
    image: "first",
    name: "Bombay Bistro",
    rating: "1.9",
    food_type: "Punjabi",
    price_for_two: 2263,
    location: "Malviya Nagar",
    distance: "8.7",
    offers: 21,
    alcohol: false,
    rest_opening_time: 19,
    rest_closing_time: 7,
  },
  {
    image: "fourth",
    name: "Taste of Punjab",
    rating: "5.0",
    food_type: "Mexican",
    price_for_two: 1891,
    location: "Janakpuri",
    distance: "5.7",
    offers: 5,
    alcohol: true,
    rest_opening_time: 0,
    rest_closing_time: 12,
  },
  {
    image: "fifth",
    name: "Spice Junction",
    rating: "3.8",
    food_type: "Continental",
    price_for_two: 1056,
    location: "Lajpat Nagar",
    distance: "8.2",
    offers: 24,
    alcohol: false,
    rest_opening_time: 1,
    rest_closing_time: 13,
  },
  {
    image: "sixth",
    name: "Delhi Darbar",
    rating: "4.1",
    food_type: "Seafood",
    price_for_two: 2404,
    location: "Rohini",
    distance: "2.0",
    offers: 24,
    alcohol: true,
    rest_opening_time: 7,
    rest_closing_time: 19,
  },
  {
    image: "eighth",
    name: "Tandoori Nights",
    rating: "1.2",
    food_type: "Vegan",
    price_for_two: 548,
    location: "Rajouri Garden",
    distance: "3.2",
    offers: 19,
    alcohol: false,
    rest_opening_time: 10,
    rest_closing_time: 22,
  },
  {
    image: "tenth",
    name: "Tandoori Nights",
    rating: "3.3",
    food_type: "Fast Food",
    price_for_two: 1656,
    location: "Saket",
    distance: "10.8",
    offers: 3,
    alcohol: false,
    rest_opening_time: 0,
    rest_closing_time: 12,
  },
  {
    image: "tenth",
    name: "Heritage Haveli",
    rating: "1.9",
    food_type: "Fast Food",
    price_for_two: 1489,
    location: "Greater Kailash",
    distance: "9.7",
    offers: 4,
    alcohol: true,
    rest_opening_time: 0,
    rest_closing_time: 12,
  },
  {
    image: "ninth",
    name: "Spice Junction",
    rating: "1.9",
    food_type: "Biryani",
    price_for_two: 1361,
    location: "Karol Bagh",
    distance: "5.8",
    offers: 1,
    alcohol: true,
    rest_opening_time: 3,
    rest_closing_time: 15,
  },
  {
    image: "fourth",
    name: "Spice Junction",
    rating: "4.9",
    food_type: "Italian",
    price_for_two: 2310,
    location: "Punjabi Bagh",
    distance: "9.6",
    offers: 3,
    alcohol: true,
    rest_opening_time: 21,
    rest_closing_time: 9,
  },
  {
    image: "fifth",
    name: "Spice Route",
    rating: "2.0",
    food_type: "Desserts",
    price_for_two: 252,
    location: "Pitampura",
    distance: "5.5",
    offers: 1,
    alcohol: true,
    rest_opening_time: 23,
    rest_closing_time: 11,
  },
  {
    image: "tenth",
    name: "Spice Route",
    rating: "2.7",
    food_type: "South Indian",
    price_for_two: 225,
    location: "Hauz Khas",
    distance: "5.2",
    offers: 8,
    alcohol: true,
    rest_opening_time: 15,
    rest_closing_time: 3,
  },
  {
    image: "second",
    name: "Delhi Darbar",
    rating: "2.8",
    food_type: "Fusion",
    price_for_two: 2000,
    location: "Lajpat Nagar",
    distance: "4.9",
    offers: 28,
    alcohol: true,
    rest_opening_time: 0,
    rest_closing_time: 12,
  },
  {
    image: "first",
    name: "Curry Leaf",
    rating: "2.9",
    food_type: "Desserts",
    price_for_two: 1886,
    location: "South Extension",
    distance: "6.0",
    offers: 0,
    alcohol: false,
    rest_opening_time: 2,
    rest_closing_time: 14,
  },
  {
    image: "sixth",
    name: "Masala House",
    rating: "2.5",
    food_type: "Continental",
    price_for_two: 599,
    location: "Saket",
    distance: "1.9",
    offers: 25,
    alcohol: true,
    rest_opening_time: 23,
    rest_closing_time: 11,
  },
  {
    image: "fifth",
    name: "Desi Bites",
    rating: "2.5",
    food_type: "North Indian",
    price_for_two: 188,
    location: "Punjabi Bagh",
    distance: "4.7",
    offers: 26,
    alcohol: false,
    rest_opening_time: 8,
    rest_closing_time: 20,
  },
  {
    image: "second",
    name: "Spice Junction",
    rating: "4.5",
    food_type: "North Indian",
    price_for_two: 265,
    location: "Lajpat Nagar",
    distance: "10.5",
    offers: 13,
    alcohol: false,
    rest_opening_time: 6,
    rest_closing_time: 18,
  },
  {
    image: "ninth",
    name: "Rasoi Express",
    rating: "1.9",
    food_type: "Chinese",
    price_for_two: 2466,
    location: "Vasant Kunj",
    distance: "9.0",
    offers: 4,
    alcohol: false,
    rest_opening_time: 10,
    rest_closing_time: 22,
  },
  {
    image: "first",
    name: "Punjabi Zaika",
    rating: "2.5",
    food_type: "Fast Food",
    price_for_two: 1721,
    location: "Rohini",
    distance: "3.7",
    offers: 16,
    alcohol: false,
    rest_opening_time: 2,
    rest_closing_time: 14,
  },
  {
    image: "tenth",
    name: "Tandoori Nights",
    rating: "2.8",
    food_type: "Vegan",
    price_for_two: 1927,
    location: "Preet Vihar",
    distance: "5.9",
    offers: 20,
    alcohol: false,
    rest_opening_time: 9,
    rest_closing_time: 21,
  },
  {
    image: "sixth",
    name: "Flavours of India",
    rating: "2.3",
    food_type: "Fast Food",
    price_for_two: 2052,
    location: "Lajpat Nagar",
    distance: "3.3",
    offers: 9,
    alcohol: false,
    rest_opening_time: 3,
    rest_closing_time: 15,
  },
  {
    image: "second",
    name: "Street Zaika",
    rating: "3.6",
    food_type: "Healthy Food",
    price_for_two: 498,
    location: "Lajpat Nagar",
    distance: "8.3",
    offers: 22,
    alcohol: false,
    rest_opening_time: 20,
    rest_closing_time: 8,
  },
  {
    image: "third",
    name: "Masala House",
    rating: "3.2",
    food_type: "Biryani",
    price_for_two: 2012,
    location: "Preet Vihar",
    distance: "9.0",
    offers: 12,
    alcohol: true,
    rest_opening_time: 11,
    rest_closing_time: 23,
  },
  {
    image: "fourth",
    name: "Street Zaika",
    rating: "3.2",
    food_type: "Vegan",
    price_for_two: 366,
    location: "Pitampura",
    distance: "3.3",
    offers: 20,
    alcohol: false,
    rest_opening_time: 20,
    rest_closing_time: 8,
  },
  {
    image: "fourth",
    name: "Spice Route",
    rating: "4.5",
    food_type: "Healthy Food",
    price_for_two: 1008,
    location: "Pitampura",
    distance: "8.4",
    offers: 4,
    alcohol: true,
    rest_opening_time: 2,
    rest_closing_time: 14,
  },
  {
    image: "tenth",
    name: "Urban Tadka",
    rating: "3.8",
    food_type: "Cafe",
    price_for_two: 888,
    location: "Hauz Khas",
    distance: "2.1",
    offers: 25,
    alcohol: true,
    rest_opening_time: 1,
    rest_closing_time: 13,
  },
  {
    image: "tenth",
    name: "Tandoori Nights",
    rating: "3.0",
    food_type: "Vegan",
    price_for_two: 1398,
    location: "Civil Lines",
    distance: "6.6",
    offers: 26,
    alcohol: false,
    rest_opening_time: 7,
    rest_closing_time: 19,
  },
  {
    image: "ninth",
    name: "Spice Junction",
    rating: "3.4",
    food_type: "South Indian",
    price_for_two: 536,
    location: "South Extension",
    distance: "10.2",
    offers: 22,
    alcohol: true,
    rest_opening_time: 15,
    rest_closing_time: 3,
  },
  {
    image: "eighth",
    name: "Kebab Kingdom",
    rating: "3.8",
    food_type: "Mughlai",
    price_for_two: 1235,
    location: "South Extension",
    distance: "9.5",
    offers: 3,
    alcohol: false,
    rest_opening_time: 17,
    rest_closing_time: 5,
  },
  {
    image: "seventh",
    name: "Royal Tandoor",
    rating: "4.0",
    food_type: "North Indian",
    price_for_two: 470,
    location: "Rajouri Garden",
    distance: "10.5",
    offers: 26,
    alcohol: true,
    rest_opening_time: 2,
    rest_closing_time: 14,
  },
  {
    image: "fourth",
    name: "Royal Tandoor",
    rating: "1.6",
    food_type: "Kebab",
    price_for_two: 1630,
    location: "Pitampura",
    distance: "1.4",
    offers: 22,
    alcohol: false,
    rest_opening_time: 4,
    rest_closing_time: 16,
  },
];

function getRestaurant(restaurants) {
  const root = document.getElementById("root");
  restaurants.forEach((restaurant) => {
    // create card container
    const card = document.createElement("div");
    card.classList.add("card");

    // create image container
    const image = document.createElement("img");
    image.src = `images/${restaurant.image}.jpg`;

    // create card_content
    const card_content = document.createElement("div");
    card_content.classList.add("card_content");

    // create card_header
    const card_header = document.createElement("div");
    card_header.classList.add("card_header");

    const h3 = document.createElement("h3");
    h3.innerText = restaurant.name;

    const rate = document.createElement("span");
    rate.innerText = `${restaurant.rating}★`;
    rate.classList.add("rating");

    card_header.appendChild(h3);
    card_header.appendChild(rate);

    // create card_footer
    const card_footer = document.createElement("div");
    card_footer.classList.add("card_footer");

    const food = document.createElement("span");
    food.innerText = restaurant.food_type;

    const price = document.createElement("span");
    price.innerText = `₹${restaurant.price_for_two} for two`;

    card_footer.appendChild(food);
    card_footer.appendChild(price);

    // create card_location
    const card_location = document.createElement("div");
    card_location.classList.add("card_footer");

    const location = document.createElement("span");
    location.innerText = restaurant.location;

    const distance = document.createElement("span");
    distance.innerText = `${restaurant.distance}km`;

    card_location.appendChild(location);
    card_location.appendChild(distance);

    card_content.appendChild(card_header);
    card_content.appendChild(card_footer);
    card_content.appendChild(card_location);

    card.appendChild(image);
    card.appendChild(card_content);

    root.appendChild(card);
  });
}

getRestaurant(restaurants);

document.getElementById("Alcohol").addEventListener("click", () => {
  const results = restaurants.filter((obj) => obj.alcohol);
  document.getElementById("root").replaceChildren();
  getRestaurant(results);
});
document.getElementById("Rating").addEventListener("click", () => {
  const results = restaurants.filter((obj) => obj.rating > 4.5);
  document.getElementById("root").replaceChildren();
  getRestaurant(results);
});

document.getElementById("Filters").addEventListener("click", () => {
  document.getElementById("filter_popup").classList.remove("hidden");
});
document.getElementById("close").addEventListener("click", () => {
  document.getElementById("filter_popup").classList.add("hidden");
});

document.getElementById("apply").addEventListener("click", () => {
  const element = document.querySelector("input[name='sort']:checked");
  const answer = element.value;

  if (answer === "rating") {
    restaurants.sort((a, b) => b.rating - a.rating);
  } else if (answer === "high-low") {
    restaurants.sort((a, b) => b.price_for_two - a.price_for_two);
  } else if (answer === "low-high") {
    restaurants.sort((a, b) => a.price_for_two - b.price_for_two);
  } else if (answer === "distance") {
    restaurants.sort((a, b) => a.distance - b.distance);
  }
  document.getElementById("filter_popup").classList.add("hidden");
  document.getElementById("root").replaceChildren();
  getRestaurant(restaurants);
});

const search_box = document.querySelector(".search-box");
search_box.addEventListener("input", (e) => {
  const term = e.target.value.toLowerCase();

  const filtered = restaurants.filter(r=>
    r.name.toLowerCase().includes(term)||
    r.food_type.toLowerCase().includes(term)||
    r.location.toLowerCase().includes(term)
  );

  document.getElementById("root").replaceChildren();
  getRestaurant(filtered ? filtered : restaurants);
});
